title: "Trung Dao"
description: |+
  Greetings! I am a Staff Machine Learning Engineer at Qualcomm AI Research, specializing in the development and optimization of cutting-edge multimodal and generative models for edge devices. My work focuses on achieving extreme efficiency without compromising performance, exemplified by pioneering distillation techniques and advanced quantization recipes. Previously, I was a Research Resident at VinAI Research, where I am fortunate to work under the mentorship of Dr. Anh Tran and Dr. Cuong Pham. My primary research interests emphasized on Deep Generative Models, including GANs and Diffusion Models.

locale: en
url: https://trung-dt.com

links:
  scholar:
    URL: https://scholar.google.com/citations?user=FZmxEYYAAAAJ&hl=en
    icon: fa-brands fa-google-scholar
  github:
    URL: https://github.com/bomcon123456
    icon: fab fa-github-alt
  linkedin:
    URL: https://www.linkedin.com/in/trung-dt880
    icon: fab fa-linkedin-in
  # kaggle:
  #   URL: https://kaggle.com/termanteus
  #   icon: fab fa-kaggle
  goodreads:
    URL: https://www.goodreads.com/user/show/106769734-trung-dao
    icon: fas fa-book

# google_analytics: UA-135929937-1
fa: https://kit.fontawesome.com/a24e8ec4a3.js

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
